# Example config file for go-irleak
# Port Number
# port: 11021
# Database options
# For MySQL or MariaDB
# dbtype: mysql
# dbparams:
#   user: david
#   dbname: irleak
#   password: This1s0ptional
#   optionalParam1: optionalVal1
#   optionalParam2: optionalVal2
# Or for SQLite
# dbtype: sqlite
# dbparams:
#   file: irleak.db
#   optionalParam1: optionalVal1
# Weather API options
# weathertype: darksky
# weatherparams:
#   key: APIkey
port: 11021
dbtype: mysql
dbparams:
    user: david
    dbname: irleak
weathertype: darksky
weatherparams:
    key: aee0f932085cdbc5776a082ca7d60be9
    lat: 39.253966
    long: -76.714454

