# Example config file for go-irleak
# Port Number
# port: 11021
# Database options
# For MySQL or MariaDB
# dbtype: mysql
# dbparams:
#   user: david
#   dbname: irleak
#   password: This1s0ptional
#   optionalParam1: optionalVal1
#   optionalParam2: optionalVal2
# Or for SQLite
# dbtype: sqlite
# dbparams:
#   file: irleak.db
#   optionalParam1: optionalVal1
# Weather API options
# weathertype: darksky
# weatherparams:
#   key: APIkey
#   lat: 0.00000
#   lon: 0.00000
